version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/pomme
    binary: pomme
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

checksum:
  name_template: 'checksums.txt'

release:
  name_template: "{{.Tag}}"

brews:
  - name: pomme
    repository:
      owner: marcusziade
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: marcusziade
      email: marcus@ziade.se
    homepage: "https://github.com/marcusziade/pomme"
    description: "A powerful CLI tool for App Store Connect analytics, sales reports, and app management"
    license: "MIT"
    test: |
      system "#{bin}/pomme", "--version"